"$schema" = 'https://starship.rs/config-schema.json'

add_newline = true

format = """
$directory $git_branch $git_status $python$rust$golang$lua$nodejs$conda 
$character"""

palette = "naqin"

[palettes.naqin]
thistle = "#CDB4DB"
amber_flame = "#FFB703"
emerald = "#06D6A0"
strawberry_red = "#E5383B"

[character]
success_symbol = "[❯](bold thistle)"
error_symbol   = "[❯](bold strawberry_red)"

[directory]
truncation_length = 3
truncate_to_repo = true
truncation_symbol = "…/"
format = "[$path]($style)"
style = "thistle"
home_symbol = "~"

[directory.substitutions]
Documents = "󰈙"
Downloads = " "
Music     = " "
Pictures  = " "

[git_branch]
symbol = "  "
format = "[$symbol$branch](bold amber_flame)"

[git_status]
format = " [($all_status$ahead_behind)]($style)"
style = "thistle"
up_to_date = '[ ✓ ](bg:overlay fg:emerald)'
untracked  = '[?\($count\)](bg:overlay fg:amber_flame)'
stashed    = '[\$](bg:overlay fg:emerald)'
modified   = '[!\($count\)](bg:overlay fg:amber_flame)'
renamed    = '[»\($count\)](bg:overlay fg:strawberry_red)'
deleted    = '[✘\($count\)](style)'
staged     = '[++\($count\)](bg:overlay fg:amber_flame)'
ahead    = '[⇡\(${count}\)](bg:overlay fg:emerald)'
diverged = '⇕[\[](bg:overlay fg:emerald)[⇡\(${ahead_count}\)](bg:overlay fg:emerald)[⇣\(${behind_count}\)](bg:overlay fg:strawberry_red)[\]](bg:overlay fg:emerald)'
behind   = '[⇣\(${count}\)](bg:overlay fg:strawberry_red)'

[python]
symbol = " 󰌠 "
format = "[$symbol$version](bold emerald)"
detect_files = ["pyproject.toml", "setup.py", "__init__.py", ".python-version"]
version_format = "v${raw}"

[rust]
symbol = " 󱘗 "
format = "[$symbol$version](bold amber_flame)"
version_format = "v${raw}"

[golang]
symbol = " 󰟓 "
format = "[$symbol$version](bold thistle)"
version_format = "v${raw}"

[lua]
symbol = " 󰢱 "
format = "[$symbol$version](bold emerald)"
detect_files = ["*.lua", ".lua-version"]
version_format = "v${raw}"

[nodejs]
symbol = " 󰌞 "
format = "[$symbol$version](bold amber_flame)"
detect_files = ["package.json", ".nvmrc", "node_modules"]
version_format = "v${raw}"

[conda]
symbol = "  "
format = "[$symbol$environment](bold emerald)"
ignore_base = true
