# Pipe any shell command as a previewer.
[[plugin.prepend_previewers]]
url = "*.csv"
run = 'piper -- bat -p --color=always "$1"'

[[plugin.prepend_previewers]]
url = "*.md"
run = 'piper -- CLICOLOR_FORCE=1 glow -w=$w -s="tokyo-night" "$1"'

[[plugin.prepend_previewers]]
url = "*.py"
run = 'piper -- bat -p --color=always "$1"'

# [[plugin.prepend_previewers]]
# url = "*.tif"
# run = 'piper -- gdalinfo "$1"'



# mime-ext.yazi
[[plugin.prepend_fetchers]]
id    = "mime" # Remove if Yazi > v26.1.22
url   = "local://*"
run   = "mime-ext.local"
prio  = "high"
group = "mime"

[[plugin.prepend_fetchers]]
id    = "mime" # Remove if Yazi > v26.1.22
url   = "remote://*"
run   = "mime-ext.remote"
prio  = "high"
group = "mime"

# naqin plugin
[[plugin.prepend_previewers]]
mime  = "image/tiff"
run   = "tif-preview"

